apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    isDefault: true
    url: http://influxdb:8086
    basicAuth: true
    basicAuthUser: admin
    user: admin
    secureJsonData:
      basicAuthPassword: my-super-secret-auth-token
      password: my-super-secret-auth-token
    database: jmeter
    jsonData:
      version: InfluxQL
    editable: true
